name: null
favicon: null
layout_spectrum: 0.02027
typography_spectrum: 0.20676
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#383838'
    - '#c7c7c7'
    - '#696969'
  brandStrength: 0
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: sign-ups
    item: e56324a1-3ea6-4310-9418-04b2ab32a5d4
    url: null
